import { FormEvent, useState } from 'react';
import { Save } from 'lucide-react';
import * as store from '../services/storageService';
import { useApp } from '../context/AppContext';
export default function Profile(){
 const a=store.getAdmin();const [name,setName]=useState(a.name);const [username,setUsername]=useState(a.username);const [password,setPassword]=useState(a.password);const [newPw,setNewPw]=useState('');const [busy,setBusy]=useState(false);const {notify}=useApp();
 const submit=(e:FormEvent)=>{e.preventDefault();store.saveAdmin({...a,name,username,password});notify('Admin profile updated.');};
 const changePw=async(e:FormEvent)=>{e.preventDefault();if(newPw.length<8){notify('Password must be at least 8 characters.','error');return}setBusy(true);const err=await store.changePassword(newPw);setBusy(false);if(err)notify(err,'error');else{setNewPw('');notify('Password changed successfully.');}};
 if(store.REMOTE)return <div><div className="admin-page-head"><div><h1>Admin Profile</h1><p>Signed in as <b>{store.adminEmail()}</b></p></div></div><form className="panel profile-form" onSubmit={changePw}><div className="field-grid"><label>New password (minimum 8 characters)<input type="password" value={newPw} onChange={e=>setNewPw(e.target.value)} autoComplete="new-password" required minLength={8}/></label></div><button className="primary-btn" type="submit" disabled={busy}><Save size={17}/> {busy?'Saving…':'Change Password'}</button></form></div>;
 return <div><div className="admin-page-head"><div><h1>Admin Profile</h1><p>Change your local admin account details.</p></div></div><form className="panel profile-form" onSubmit={submit}><div className="field-grid"><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>Password<input type="text" value={password} onChange={e=>setPassword(e.target.value)} required minLength={4}/></label></div><div className="warning">This authentication is stored in your browser's Local Storage. It is not secure server-side authentication and should not be used as the sole protection for a production website.</div><button className="primary-btn" type="submit"><Save size={17}/> Save Profile</button></form></div>}
